### ISSUE TITLE
Переименовать название функции no_check_text

### ISSUE THREAD

**Issue by stereotype013** [alexeyhripunov/SurfCustomCalabash#3]
Правильнее назвать check_no_text
В идеале бы как то сделать, чтобы обе функции работали, потому что если переименовывать, то отвалится в некоторых проектах наверное. Функция где то на 192 строчке в Common

**Comment by vrnvorona** [comment]
Добавить новую нормальную, в старую добавить вывод в консоль про то что функция deprecated

**Comment by alexeyhripunov** [comment]
Fixed 0.2.0
